# Generated by Django 4.2.4 on 2023-11-19 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='todlist',
            new_name='todolist',
        ),
    ]
